services:
  # Servicio de la Base de Datos (sin cambios)
  db:
    image: mysql:5.7
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: userpass
      MYSQL_DATABASE: smart_home
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-puserpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de la API (con Dockerfile por defecto)
  api:
    build:
      context: ./src/backend      # Busca un 'Dockerfile' por defecto en esta carpeta
    ports:
      - "8000:3000"
    volumes:
      - ./src/backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Servicio de Frontend (con Dockerfile por defecto)
  frontend:
    build:
      context: ./src/frontend     # Busca un 'Dockerfile' por defecto en esta carpeta
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
